In [4]:
import pandas as pd
import os

frames = []

for file_name in os.listdir('results'):
    if file_name == '.DS_Store':
      continue
    fn = pd.read_csv('results/'+file_name)
    frames.append(fn)
    
data = pd.concat(frames)
print(data)

   image_name  category
0       0.jpg       103
1       1.jpg        48
2      10.jpg         0
3     100.jpg       109
4    1000.jpg        97
5    1001.jpg        62
6    1002.jpg       103
7    1003.jpg         9
8    1004.jpg        78
9   10000.jpg        93
10  10001.jpg        91
11  10002.jpg        79
12  10003.jpg       120
13  10004.jpg        45
14  10005.jpg       108
15  10006.jpg        12
16  10007.jpg        69
17  10008.jpg        42
18  10009.jpg        52
19  10010.jpg        44
20  10011.jpg        12
21  10012.jpg        91
22  10013.jpg        32
23  10014.jpg       100
24  10015.jpg        12
25  10016.jpg        12
26  10017.jpg        16
27  10018.jpg        96
28  10019.jpg        62
29  10020.jpg        45
..        ...       ...
20  10057.jpg         1
21  10058.jpg       126
22  10059.jpg        73
23  10060.jpg       102
24  10061.jpg       130
25  10062.jpg        79
26  10063.jpg        76
27  10064.jpg        68
28  10065.jpg        44
29  10066.jpg       114
30  10067.jpg        40
31  10068.jpg        69
32  10069.jpg        48
33  10070.jpg         5
34  10071.jpg         7
35  10072.jpg        53
36  10073.jpg       125
37  10074.jpg       125
38  10075.jpg        64
39  10076.jpg        25
40  10077.jpg        87
41  10078.jpg       106
42  10079.jpg        28
43  10080.jpg        43
44  10081.jpg        21
45  10082.jpg        53
46  10083.jpg       103
47  10084.jpg        25
48  10085.jpg         7
49  10086.jpg        12

[100 rows x 2 columns]

In [5]:
data['indexNumber'] = [int(i.split('.')[0]) for i in data['image_name']]
# Perform sort of the rows
data.sort_values(by=['indexNumber'], ascending = [True], inplace = True)
# Deletion of the added column
data.drop('indexNumber', 1, inplace = True)
print(data)

   image_name  category
0       0.jpg       103
1       1.jpg        48
2      10.jpg         0
3     100.jpg       109
4    1000.jpg        97
5    1001.jpg        62
6    1002.jpg       103
7    1003.jpg         9
8    1004.jpg        78
0    1005.jpg        69
1    1006.jpg        54
2    1007.jpg        41
3    1008.jpg       107
9   10000.jpg        93
10  10001.jpg        91
11  10002.jpg        79
12  10003.jpg       120
13  10004.jpg        45
14  10005.jpg       108
15  10006.jpg        12
16  10007.jpg        69
17  10008.jpg        42
18  10009.jpg        52
19  10010.jpg        44
20  10011.jpg        12
21  10012.jpg        91
22  10013.jpg        32
23  10014.jpg       100
24  10015.jpg        12
25  10016.jpg        12
..        ...       ...
20  10057.jpg         1
21  10058.jpg       126
22  10059.jpg        73
23  10060.jpg       102
24  10061.jpg       130
25  10062.jpg        79
26  10063.jpg        76
27  10064.jpg        68
28  10065.jpg        44
29  10066.jpg       114
30  10067.jpg        40
31  10068.jpg        69
32  10069.jpg        48
33  10070.jpg         5
34  10071.jpg         7
35  10072.jpg        53
36  10073.jpg       125
37  10074.jpg       125
38  10075.jpg        64
39  10076.jpg        25
40  10077.jpg        87
41  10078.jpg       106
42  10079.jpg        28
43  10080.jpg        43
44  10081.jpg        21
45  10082.jpg        53
46  10083.jpg       103
47  10084.jpg        25
48  10085.jpg         7
49  10086.jpg        12

[100 rows x 2 columns]